export const BASE_URL = "https://alumni-backend-8eqk.onrender.com"
export const USERS_URL = "/api/users"
export const ACADMIC_URL = "/api/academics"
export const JOBDETAIL_URL = "/api/jobDetail"
export const DONATION_URL = "/api/donation"
